apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ecommerce.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
{{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
